In [1]:
import pandas as pd

In [11]:
df = pd.read_csv('dataNom_1Q022025.csv').query('concepto in [1, 7]')[['codigo', 'percosto', 'periodopagado', 'del', 'al', 'dias', 'cedula', 'concepto', 'vrconcepto']];

In [12]:
df

,codigo,percosto,periodopagado,del,al,dias,cedula,concepto,vrconcepto
0,HDP9644,1Q022025,SY012025,2025-01-11,2025-01-25,1,1020781912,1,47450.0
1,HDP9644,1Q022025,SY012025,2025-01-11,2025-01-25,1,1020781912,7,83038.0
7,HES3863,1Q022025,SR012025,2025-01-11,2025-01-25,5,32837863,1,237250.0
12,HES3867,1Q022025,SR012025,2025-01-11,2025-01-25,3,43255588,1,142350.0
17,HES3861,1Q022025,SW012025,2025-01-11,2025-01-25,4,1035282132,1,189800.0
...,...,...,...,...,...,...,...,...,...
10037,HDA1981,1Q022025,PH022025,2025-02-01,2025-02-15,1,28653127,7,83038.0
10042,HDA2002,1Q022025,PH022025,2025-02-01,2025-02-15,5,1002353722,1,237251.0
10048,HDA2010,1Q022025,PH022025,2025-02-01,2025-02-15,1,1006156130,1,47450.0
10053,HDA1976,1Q022025,PH022025,2025-02-01,2025-02-15,12,1010226740,1,569402.0
10059,HDA2011,1Q022025,PH022025,2025-02-01,2025-02-15,1,1047503617,1,47450.0